version: '3.8'

services:
  api:
    build:
      context: ./backend/billing-service
    container_name: billing-api
    env_file:
      - ./backend/billing-service/.env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: billing-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: billingdb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  postgres-test:
    image: postgres:16
    container_name: postgres-test
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: billingdb_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d billingdb_test"]
      interval: 5s
      timeout: 5s
      retries: 5
